# Generated by Django 2.2.7 on 2020-01-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_insurance', models.BooleanField(default=False)),
                ('vehicle_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chases_no', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=30)),
                ('vehicle_registration', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('model', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('id_no', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=200)),
                ('commencing_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('insurance_image', models.FileField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='vehicle.Cars')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='vehicle.Owner'),
        ),
        migrations.AddField(
            model_name='cars',
            name='logbook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehicle.Logbook'),
        ),
    ]
