# Generated by Django 2.2.7 on 2020-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200128_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
